#!/usr/bin/env python3
"""
Generate journal open-data table, bar chart, CSV, and markdown summary.

Queries pmid_registry.duckdb for per-journal open data rates and produces:
  - latex/tables/table_journals.tex       (longtable, Weibull threshold)
  - latex/figures/journals_open_data.png   (bar chart, Weibull threshold)
  - results/journals_summary.csv          (all journals, min articles)
  - results/journals_summary.md           (ranked table)
"""

import argparse
import logging
import sys
from datetime import date
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import pandas as pd

# Allow running as `python scripts/table_journals.py` from repo root
sys.path.insert(0, str(Path(__file__).resolve().parent))
from utils.data_loader import (
    connect_duckdb_registry,
    query_journal_open_data_stats,
    query_baseline_od_rate,
)
from utils.latex_helpers import (
    escape_latex,
    format_number_siunitx,
    get_color_bwr,
)
from table_funders import compute_weibull_threshold

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Bar chart
# ---------------------------------------------------------------------------
def generate_journal_bar_chart(
    df: pd.DataFrame,
    output_path: Path,
    threshold: int = 0,
    baseline_pct: float | None = None,
) -> None:
    """Horizontal bar chart of journals above the Weibull threshold."""
    top = df[df["total_articles"] >= threshold].copy() if threshold > 0 else df.copy()
    top.sort_values("open_data_pct", ascending=False, inplace=True)

    if top.empty:
        logger.warning("No journals above threshold %d for figure", threshold)
        return

    top = top.iloc[::-1]  # reverse so highest is at top of chart
    n_journals = len(top)

    labels = [
        name[:50] + "..." if len(name) > 50 else name
        for name in top["journal"].values
    ]
    observed = top["open_data_pct"].values
    totals = top["total_articles"].values

    # Color: total articles on log scale using YlOrRd colormap
    norm = mcolors.LogNorm(vmin=max(totals.min(), 1), vmax=totals.max())
    cmap = plt.cm.YlOrRd
    colors = [cmap(norm(t)) for t in totals]

    fig, ax = plt.subplots(figsize=(10, 0.45 * n_journals + 2.0))

    bars = ax.barh(
        range(n_journals), observed,
        color=colors, edgecolor="grey", linewidth=0.3,
    )
    max_val = observed.max()

    for bar, val in zip(bars, observed):
        ax.text(
            bar.get_width() + 0.3, bar.get_y() + bar.get_height() / 2,
            f"{val:.1f}%", va="center", fontsize=8,
        )

    ax.set_yticks(range(n_journals))
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("% Articles with Open Data Statement", fontsize=11)
    ax.set_title("Open Data Rates Among Top Journals", fontsize=13, fontweight="bold")

    # Colorbar for total articles
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, pad=0.02, aspect=30, shrink=0.8)
    cbar.set_label("Total Articles", fontsize=10)

    # Baseline line
    if baseline_pct is not None:
        ax.axvline(baseline_pct, color="grey", linestyle="--", linewidth=1, alpha=0.7)
        ax.text(
            baseline_pct + 0.3, -0.8,
            f"Overall baseline: {baseline_pct:.1f}%",
            fontsize=8, color="grey", va="top",
        )

    ax.set_xlim(0, max_val * 1.15)
    plt.tight_layout()
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    logger.info("Wrote figure: %s (%d journals)", output_path, n_journals)


# ---------------------------------------------------------------------------
# LaTeX table generation
# ---------------------------------------------------------------------------
def generate_journal_latex_table(
    df: pd.DataFrame,
    output_path: Path,
    threshold: int = 0,
    n_total_journals: int = 0,
    survival_pct: float = 1.0,
    label_suffix: str = "",
) -> None:
    """Write a longtable .tex file for journals above the threshold."""
    top = df[df["total_articles"] >= threshold].copy() if threshold > 0 else df.copy()
    top.sort_values("open_data_pct", ascending=False, inplace=True)

    if top.empty:
        logger.warning("No journals above threshold %d for table", threshold)
        return

    min_total = top["total_articles"].min()
    max_total = top["total_articles"].max()
    min_pct = top["open_data_pct"].min()
    max_pct = top["open_data_pct"].max()

    lines = []
    lines.append(r"% Auto-generated by scripts/table_journals.py — do not edit manually")
    lines.append(r"\begingroup")
    lines.append(r"\arrayrulecolor{COL5}")
    lines.append(r"\rowcolors{2}{COL5!10}{white}")
    lines.append(r"\small")

    col_spec = r"p{6cm} S[table-format=6.0] S[table-format=5.0] S[table-format=2.1]"
    n_cols = 4
    lines.append(rf"\begin{{longtable}}{{{col_spec}}}")

    surv_str = f"{survival_pct:g}"
    caption = (
        r"Open data rates among top biomedical journals. "
        rf"Journals exceeding the Weibull-derived {surv_str}\% survival threshold "
        rf"for total articles ($\geq${threshold:,} articles with "
        r"oddpub v7 coverage), ranked by open data rate. "
        r"Cell shading: Total Pubs uses a blue-to-red gradient on log scale; "
        r"\% Open Data uses a linear blue-to-red gradient. "
        rf"Full rankings for all {n_total_journals:,} journals are available "
        r"in the supplementary materials on GitHub."
    )
    lines.append(rf"\caption{{{caption}}}")
    lines.append(rf"\label{{tab:journals{label_suffix}}} \\")

    header_row = (
        r"\textbf{Journal} & "
        r"{\textbf{Total Pubs}} & {\textbf{Open Data}} & "
        r"{\textbf{\% Open Data}} \\"
    )
    lines.append(r"\toprule")
    lines.append(header_row)
    lines.append(r"\midrule")
    lines.append(r"\endfirsthead")
    lines.append(r"\toprule")
    lines.append(header_row)
    lines.append(r"\midrule")
    lines.append(r"\endhead")
    lines.append(r"\midrule")
    lines.append(
        rf"\multicolumn{{{n_cols}}}{{r}}{{\textit{{Continued on next page\ldots}}}} \\"
    )
    lines.append(r"\endfoot")
    lines.append(r"\bottomrule")
    lines.append(r"\endlastfoot")

    # Data rows
    for _, row in top.iterrows():
        name = escape_latex(str(row["journal"]))
        total = format_number_siunitx(row["total_articles"])
        od = format_number_siunitx(row["open_data_articles"])
        pct = f"{row['open_data_pct']:.1f}"

        color_total = get_color_bwr(row["total_articles"], min_total, max_total, use_log=True)
        color_pct = get_color_bwr(row["open_data_pct"], min_pct, max_pct)

        lines.append(
            f"{name} & "
            f"\\cellcolor{color_total} {total} & "
            f"\\cellcolor{color_pct} {od} & "
            f"\\cellcolor{color_pct} {pct} \\\\"
        )

    lines.append(r"\end{longtable}")
    lines.append(r"\arrayrulecolor{black}")
    lines.append(r"\endgroup")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote LaTeX table: %s (%d journals)", output_path, len(top))


# ---------------------------------------------------------------------------
# CSV output
# ---------------------------------------------------------------------------
def save_summary_csv(df: pd.DataFrame, output_path: Path) -> None:
    """Save the full journal summary as CSV."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)
    logger.info("Wrote CSV summary: %s (%d rows)", output_path, len(df))


# ---------------------------------------------------------------------------
# Markdown output
# ---------------------------------------------------------------------------
def save_summary_markdown(
    df: pd.DataFrame,
    output_path: Path,
    baseline_pct: float = 0.0,
) -> None:
    """Save the full journal summary as markdown."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("# Journal Open Data Rankings")
    lines.append("")
    lines.append(f"> Generated {date.today().isoformat()} from pmid_registry.duckdb")
    lines.append(f"> {len(df):,} journals with oddpub v7 coverage")
    lines.append(f"> Overall baseline: {baseline_pct:.1f}% open data")
    lines.append("")

    lines.append(
        "| Rank | Journal | Total Pubs | Open Data | % Open Data |"
    )
    lines.append(
        "|---:|---|---:|---:|---:|"
    )

    for rank, (_, row) in enumerate(df.iterrows(), 1):
        name = str(row["journal"])
        total = f"{int(row['total_articles']):,}"
        od = f"{int(row['open_data_articles']):,}"
        pct = f"{row['open_data_pct']:.1f}%"
        lines.append(f"| {rank} | {name} | {total} | {od} | {pct} |")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote markdown summary: %s (%d rows)", output_path, len(df))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--duckdb-path",
        default="/data/adamt/osm/datalad-osm/duckdbs/pmid_registry.duckdb",
        help="Path to pmid_registry.duckdb",
    )
    p.add_argument(
        "--output-dir",
        default=str(Path(__file__).resolve().parent.parent / "latex" / "tables"),
        help="Directory for LaTeX table output",
    )
    p.add_argument(
        "--figures-dir",
        default=str(Path(__file__).resolve().parent.parent / "latex" / "figures"),
        help="Directory for figure output",
    )
    p.add_argument(
        "--results-dir",
        default=str(Path(__file__).resolve().parent.parent / "results"),
        help="Directory for CSV and markdown output",
    )
    p.add_argument(
        "--figure-survival", type=float, default=0.005,
        help="Weibull survival for figure threshold (default: 0.005 = 0.5%%)",
    )
    p.add_argument(
        "--table-survival", type=float, default=0.01,
        help="Weibull survival for table threshold (default: 0.01 = 1%%)",
    )
    p.add_argument("--min-articles", type=int, default=100, help="Minimum articles for CSV/markdown")
    p.add_argument("--year-from", type=int, default=None, help="Filter by pub_year >=")
    p.add_argument("--year-to", type=int, default=None, help="Filter by pub_year <=")
    p.add_argument("--date-from", default=None, help="Filter by pub_date >= (YYYY-MM-DD)")
    p.add_argument("--date-to", default=None, help="Filter by pub_date <= (YYYY-MM-DD)")
    p.add_argument("--research-only", action="store_true", help="Only include research articles")
    p.add_argument("--output-suffix", default="", help="Suffix for output filenames")
    p.add_argument("--verbose", action="store_true")
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    logger.info("Connecting to DuckDB: %s", args.duckdb_path)
    con = connect_duckdb_registry(args.duckdb_path)

    # Date / year / research filters
    filter_kwargs = {}
    parts = []
    if args.date_from:
        filter_kwargs["date_from"] = args.date_from
        parts.append(f"pub_date >= {args.date_from}")
    elif args.year_from:
        filter_kwargs["year_from"] = args.year_from
        parts.append(f"pub_year >= {args.year_from}")
    if args.date_to:
        filter_kwargs["date_to"] = args.date_to
        parts.append(f"pub_date <= {args.date_to}")
    elif args.year_to:
        filter_kwargs["year_to"] = args.year_to
        parts.append(f"pub_year <= {args.year_to}")
    if args.research_only:
        filter_kwargs["research_only"] = True
        parts.append("research only")
    if parts:
        logger.info("Filters: %s", ", ".join(parts))

    # Query per-journal stats
    logger.info("Running journal stats query (min_articles=%d)...", args.min_articles)
    journal_stats = query_journal_open_data_stats(
        con, min_articles=args.min_articles, **filter_kwargs,
    )
    logger.info("  %d journals with >= %d articles", len(journal_stats), args.min_articles)

    # Compute baseline OD rate
    baseline = query_baseline_od_rate(con, **filter_kwargs)
    baseline_pct = baseline["baseline_pct"]
    logger.info(
        "  Overall baseline: %d / %d = %.1f%%",
        baseline["open_data_articles"], baseline["total_articles"], baseline_pct,
    )

    # Compute percentages
    journal_stats["open_data_pct"] = (
        100.0 * journal_stats["open_data_articles"] / journal_stats["total_articles"]
    ).round(1)
    journal_stats["open_code_pct"] = (
        100.0 * journal_stats["open_code_articles"] / journal_stats["total_articles"]
    ).round(1)

    # Sort by OD rate descending
    journal_stats.sort_values("open_data_pct", ascending=False, inplace=True)
    journal_stats.reset_index(drop=True, inplace=True)

    # Weibull thresholds
    article_counts = journal_stats["total_articles"].values

    fig_threshold, fig_n, fig_params = compute_weibull_threshold(
        article_counts, survival=args.figure_survival, min_articles=args.min_articles,
    )
    logger.info(
        "  Weibull %.1f%% figure threshold: >=%s articles → %d journals (shape=%.3f)",
        args.figure_survival * 100, f"{fig_threshold:,}", fig_n, fig_params[0],
    )

    tbl_threshold, tbl_n, tbl_params = compute_weibull_threshold(
        article_counts, survival=args.table_survival, min_articles=args.min_articles,
    )
    logger.info(
        "  Weibull %.1f%% table threshold: >=%s articles → %d journals (shape=%.3f)",
        args.table_survival * 100, f"{tbl_threshold:,}", tbl_n, tbl_params[0],
    )

    # Build filtered subsets
    fig_df = journal_stats[journal_stats["total_articles"] >= fig_threshold].copy()
    tbl_df = journal_stats[journal_stats["total_articles"] >= tbl_threshold].copy()

    # Outputs
    sfx = args.output_suffix
    table_path = Path(args.output_dir) / f"table_journals{sfx}.tex"
    figure_path = Path(args.figures_dir) / f"journals_open_data{sfx}.png"
    csv_path = Path(args.results_dir) / f"journals_summary{sfx}.csv"
    md_path = Path(args.results_dir) / f"journals_summary{sfx}.md"

    generate_journal_latex_table(
        tbl_df, table_path,
        threshold=tbl_threshold,
        n_total_journals=len(journal_stats),
        survival_pct=args.table_survival * 100,
        label_suffix=sfx,
    )
    generate_journal_bar_chart(
        fig_df, figure_path,
        threshold=0,
        baseline_pct=baseline_pct,
    )
    save_summary_csv(journal_stats, csv_path)
    save_summary_markdown(journal_stats, md_path, baseline_pct=baseline_pct)

    con.close()
    logger.info("Done.")


if __name__ == "__main__":
    main()
